### ISSUE TITLE
课程已看完程序内显示请先完成之前的学习

### ISSUE THREAD

**Issue by Gxyloj** [dirname/minghuaetc-hack-CSharp#1]
武工院 orgid = 5
课程4262 
第二章观看完前4节后第5节显示“请先完成之前的学习”，网页端可以正常观看第5节，手动观看完第5、6节后第5节及后续课程仍然显示“请先完成之前的学习”

**Comment by dirname** [comment]
> 武工院 orgid = 5
> 课程4262
> 第二章观看完前4节后第5节显示“请先完成之前的学习”，网页端可以正常观看第5节，手动观看完第5、6节后第5节及后续课程仍然显示“请先完成之前的学习”

你看一下现在这个新的版本，试试
